# Generated by Django 3.2.7 on 2021-10-09 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0002_auto_20211002_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salesman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.TextField(blank=True, null=True, verbose_name='Продавец')),
                ('phone', models.FloatField(blank=True, null=True, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Продавец',
                'verbose_name_plural': 'Продавцы',
                'ordering': ['person'],
            },
        ),
        migrations.AddField(
            model_name='bb',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bboard.salesman', verbose_name='Продавец'),
        ),
    ]
